ecommerceproject/ecommerceproject/urls.py
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from django.contrib import admin

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('shop.urls')),

]
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)

    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ecommerceproject/shop/urls.py
from . import views
from django.urls import path

app_name = 'shop'

urlpatterns = [

    path('', views.allProdCat, name='allProdCat'),
    path('<slug:c_slug>/', views.allProdCat, name='products_by_category'),
    path('<slug:c_slug>/<slug:product_slug>/', views.proDetail, name='prodCatdetail'),
]

ecommerceproject/shop/models.py
from django.db import models
from django.urls import reverse


class Category(models.Model):

    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    image=models.ImageField(upload_to='category',blank=True)


    class Meta:
        ordering=("name",)
        verbose_name='category'
        verbose_name_plural='categories'

    def __str__(self):
        return '{}'.format(self.name)

    def get_url(self):
        return reverse('shop:products_by_category',args=[self.slug])


class Product(models.Model):
    name=models.CharField(max_length=250,unique=True)
    slug=models.SlugField(max_length=250,unique=True)
    description=models.TextField(blank=True)
    price=models.DecimalField(max_digits=10,decimal_places=2)
    category=models.ForeignKey(Category,on_delete=models.CASCADE)
    image=models.ImageField(upload_to='product',blank=True)
    stock=models.IntegerField()
    available=models.BooleanField(default=True)
    created=models.DateTimeField(auto_now_add=True)
    updated=models.DateTimeField(auto_now=True)
#Create your models here.
    def get_url(self):
        return reverse('shop:prodCatdetail', args=[self.category.slug,self.slug])

    class Meta:
        ordering=("name",)
        verbose_name='product'
        verbose_name_plural='products'

    def __str__(self):
        return '{}'.format(self.name)

ecommerceproject/shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product


# Create your views here.
def allProdCat(request, c_slug=None):
    c_page = None
    products = None

    if c_slug != None:
        c_page = get_object_or_404(Category, slug=c_slug)
        products = Product.objects.all().filter(category=c_page, available=True)
    else:
        products = Product.objects.all().filter(available=True)
    return render(request, 'category.html', {'category': c_page, 'products': products})


def proDetail(request, c_slug, product_slug):
    try:
        product = Product.objects.get(category__slug=c_slug)
    except Exception as e:
     raise e
    return render(request, 'product.html', {'product': product})

ecommerceproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="{% static 'bootstrap.min.css' %}" rel="stylesheet">

    <meta name='description' content='{% block metadescription %}{% endblock %}'>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
<div class="container">
    {% include 'header.html' %}
    {% include 'nav.html' %}

{% block content %}
{% endblock %}

</div>

{% include 'footer.html' %}
<script src="{% static 'js/bundle.min.js' %}"></script>



</body>
</html>

ecommerceproject/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
    {% if category %}
        {{ category.description|truncatewords:155 }}
    {% else %}
         Welcome to the world of FK
    {% endif %}
{% endblock %}

{% block title %}
{% if category %}
    {{ category.name }}-FlopKart
  {% else %}
     See our Collection in FK
{% endif %}
{% endblock %}

{% block content %}
{% if category %}

   <div>
       <div>
          <p><a href="{% url 'shop:allProdCat' %}"> Our Products Collections </a>"</p>
       </div>
   </div>
{% endif %}

<div>
    {% if category %}
         <img src="{{category.image.url}}" alt={{category.name}}>
</div>
    <br>
<div>
    <h1>{{category.name}}</h1>
    <p>{{category.description}}</p>
</div>
    {% else %}
<div>
     <img src="{% static 'img/banner.png' %}" alt="all products" style="width:1500px;height:550px;">
</div>
<br>
<div>
    <h1>Our Products Collection</h1>
    <p>Dummy Content</p>
</div>
    {% endif %}
<div>
    <div>
        {% for product in products %}
        <div>
            <div>
                <a href="{{product.get_url}}"><img src="{{product.image.url}}" alt="={{product.name}}"></a>
                <div>
                    <h4>{{product.name}}</h4>
                    <p>{{product.price}}</p>
                </div>

            </div>
        </div>
        {% endfor %}

    </div>
</div>
{% endblock %}

ecommerceproject/templates/footer.html
<div>
    <p>&copy;FlopKart Kochi Pvt.Ltd.All rights reserved.</p>
</div>

ecommerceproject/templates/header.html
{% load static %}
<header>
    <center>
       <a href="{%url 'shop:allProdCat' %}"></a> <img src="{% static 'img/fk.png' %}"alt="logoimage" style="width:300px;height:300px;">

    </center>
</header>

ecommerceproject/templates/nav.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNavDropdown">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Features</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Pricing</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown link
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
      </ul>
    </div>
  </div>
</nav>


<nav>
  <ul>
    <li>
      <a href="{% url 'shop:allProdCat' %}">All Products</a>
    </li>
    {% for cat in links %}
    <li><a href="{{cat.get_url}}">{{cat.name}}</a></li>
    {% endfor %}

    <li>Your cart</li>
  </ul>
</nav>

ecommerceproject/templates/product.html
{% extends 'base.html' %}
{% load static %}
{% block metadescription %}
   {{ product.description | truncatewords:155 }}
{% endblock %}

{% block title %}
    {% if category %}
    {{ product.name }}-FlopKart

    {% endif %}
{% endblock %}

{% block content %}
<div>
    <div>
         <p><a href ="{% url 'shop:allProdCat' %}"> Home </a>"</p> | <a href ="{{product.category.get_url }}></a> | {{product.name}}"
    </div>
</div>
<br>>
<div>
    <div>
        <div>
            <img src="product.image.url" alt="{{product.name}}">

        </div>
    </div>
<div>
    <div>
        <h1>{{product.name}}</h1>
        <p>${{product.price}}</p>
        <p>Product Description</p>
        <p>{{product.description}}</p>
        {% if product.stock <= 0 %}
        <p><b> Out of Stock</b></p>
        {% else %}
        <a href ="">Add to Cart</a>
        {% endif %}

    </div>
</div>
</div>
{% endblock %}